### ISSUE TITLE
Dynamically position last-updated textblock

### ISSUE THREAD

**Issue by jidicula** [jidicula/jidicula-resume#1]
Currently, the last-updated `textblock` in the first page header is positioned by its left edge relative to the left side of the page.

However, with this configuration the shorter month names (like May) will result in unnecessary space between the right edge of the `textblock` and the right edge of the page.

Instead:
- [ ] The `textblock` should be positioned by its right edge relative to the right side of the page. Investigate a robust way of achieving this.
- [ ] The text inside should be `raggedleft`.

**Comment by jidicula** [comment]
@dbenjaminmiller any ideas for this?

**Comment by dbenjaminmiller** [comment]
What you have done with `\livelocation` and `\lastupdated` makes no sense. You should use scrheadings instead, or, if you must use these macros inline, redefine each of them to *just produce text*, so that `\livelocation` produces `The current version is at foo.bar/foo` and `\lastupdated` produces `Last updated on \today`. Then you can just have a line which is `\livelocation\hfill\lastupdated`. Why you have used the Deedy-Resume template (which does things in this highly unidiomatic and silly way) I do not know.
Ed.: I suppose I can understand why the two are supposed to be like they are, for the class; I'd initially taken them to be text commands when viewing them in the .tex file. But still, it makes no sense. Just use an actual headings package, or \hfill, and don't engage in the positioning-related nonsense this class does.

**Comment by jidicula** [comment]
> Then you can just have a line which is `\livelocation\hfill\lastupdated`.

Oh yeah this makes much more sense, thanks!
